export const skillsData = [
  'React',
  'Next.js',
  'TypeScript',
  'Flutter',
  'Redux',
  'Context API',
  'React Query',
  'React Table',
  'Formik',
  'React Hook Form',
  'Yup',
  'Zod',
  'Webpack',
  'RESTful APIs',
  'CSS',
  'SCSS',
  'TailwindCSS',
  'Git',
  'Storybook',
  'React Dev Tool',
  'Framer Motion',
  'Figma',
  'UX/UI',
  'Project Management',
  'Problem Solving',
  'Detail Oriented',
];
